### ISSUE TITLE
Time and/or spatial gaps in trajectories

### ISSUE THREAD

**Issue by ViktorNorrsjo** [MobilityDB/MobilityDB#187]
Hi

Is there a simple way to construct trajectories (sequences object) which are split at time and/or spatial gaps?
I have followed the example but used the constructor function "tgeompoint_seqset" but only one trajectory is created (See figure).  

In this example I want to split the trajectory on the left hand side, on several occasions, where there are both time and spatial gaps between instances.

![mobilitydb_traj](https://user-images.githubusercontent.com/62289295/154039704-79092bc7-a510-431d-ac53-48d7e8c869bc.png)

Thank you.

**Comment by estebanzimanyi** [comment]
You can always extract from a temporal sequence set the list of composing temporal sequences with the function `sequences()`
https://docs.mobilitydb.com/MobilityDB/develop/ch05s04.html
which returns a PostgreSQL array of temporal sequences. You can then apply the PostgreSQL `unnest()` function to obtain each of the temporal sequences in the array in a single row.
```
SELECT astext(unnest(sequences(tgeompoint '{[Point(1 1)@2000-01-01, Point(2 2)@2000-01-02],
  [Point(2 2)@2000-01-03, Point(1 1)@2000-01-04]}')));
                                 astext
------------------------------------------------------------------------
 [POINT(1 1)@2000-01-01 00:00:00+01, POINT(2 2)@2000-01-02 00:00:00+01]
 [POINT(2 2)@2000-01-03 00:00:00+01, POINT(1 1)@2000-01-04 00:00:00+01]
(2 rows)
```
Does this answer your question ?

**Comment by ViktorNorrsjo** [comment]
In my example here I have the following dataset
![issue](https://user-images.githubusercontent.com/62289295/154692368-448e66cb-6242-4fc6-980b-f246a4bc2a8e.png)
The data have bigger spatial and time gaps between two points compared to the rest. The question is if there is a way to create two trips from this data instead of one? The split should be based on the spatial and time gap. 

From the constructor function "tgeompoint_seqset" 
https://docs.mobilitydb.com/MobilityDB/develop/ch05s02.html
only one temporal sequence is created (black line)

![issue_traj](https://user-images.githubusercontent.com/62289295/154693981-a8e2d531-a99a-4499-b666-c4af1a038c55.png)

**Comment by estebanzimanyi** [comment]
Determining what is a spatial and/or temporal gap is application dependent,
so the constructors in MobilityDB just connect all points. Determining when
there is a gap should be done on a preprocessing step.

However, this is a common requirement that we need to tackle by defining an
appropriate API. The following questions arise to my mind
* How would you determine when there should be a spatial and/or temporal
gap?
* How to represent those gaps in MobilityDB? I would represent them by a
periodset value. Then a simple operation minusPeriodset(trajectory, gaps)
will simply construct the expected result from the result of the current
constructors. Then there is the question of whether we would design a new
constructor that has in addition a parameter for the gaps, instead of
calling first the constructor and then the minusPeriodset operation.

Please let me know your thoughts about this.

**Comment by ViktorNorrsjo** [comment]
After some small adjustments to the function, [splitTrajectoriesOnGaps.txt](https://github.com/MobilityDB/MobilityDB/files/8108832/splitTrajectoriesOnGaps.txt), it works like a charm. 

Thank you. It helped plenty

**Comment by estebanzimanyi** [comment]
Dear Viktor
We have implemented a built-in function for this in the develop branch. 
```
SELECT asText(tgeompoint_seqset_gaps(ARRAY[tgeompoint 'Point(1 1)@2000-01-01',
'Point(2 2)@2000-01-02', 'Point(3 2)@2000-01-03', 'Point(3 2)@2000-01-05'], true, 1, '1 day'));
-- {[POINT(1 1)@2000-01-01], [POINT(2 2)@2000-01-02, POINT(3 2)@2000-01-03], [POINT(3 2)@2000-01-05]}
```
The signature of the function is as follows
```
tcont_seqset_gaps(ttype_inst[],linear=true,maxdist=0.0,maxt=’0 minutes’): tcont_seqset
```
This function should be much faster than the PL/pgSQL function. If by chance you test the function, we would be grateful to know how it worked wrt the previous one.
