### ISSUE TITLE
Data types precision?

### ISSUE THREAD

**Issue by apiszcz** [MobilityDB/MobilityDB#250]
I may have missed it in the manual, is there a list of the data types and precision? 
Is the time precision limited to 1 second intervals or does it support micro seconds (e.g. postgres timestamp)
https://www.postgresql.org/docs/current/datatype.html

Furthermore, MobilityDB
uses four time types to represent extents of time: the timestamptz type provided by PostgreSQL and three new types which
are period, timestampset, and periodset. In addition, two range types are defined in MobilityDB: intrange and
floatrange.

**Comment by estebanzimanyi** [comment]
MobilityDB uses PostgreSQL's time data types (timestamp, timestamptz, interval) and thus has the same characteristics (including precision) as in PostgreSQL. MobilityDB's timestampset is conceptually an array of timestamptz.

MobilityDB 1.0 uses int4range and float8range from PostgreSQL range types and defines the period type, which is a more efficient version of PostgreSQL's tstzrange type. In the forthcoming version 1.1 these range types are replaced by MobilityDB's built-in span types, which are more efficient versions of PostgresSQL range types. MobilityDB's period set type is conceptually 
an array of periods.

MobilityDB uses period, tbox, and stbox as bouding box types.

MobilityDB uses PostgreSQL types boolean, integer, float, and text and PostGIS types geometry and geography (restricted to points) as base types for temporal types, which are then used for defining the temporal types.

Does this answer your question ?

**Comment by apiszcz** [comment]
Yes, thank you for the thorough answer.

**Comment by belug23** [comment]
> MobilityDB 1.0 uses int4range and float8range from PostgreSQL range types and defines the period type, which is a more efficient version of PostgreSQL's tstzrange type. In the forthcoming version 1.1 these range types are replaced by MobilityDB's built-in span types, which are more efficient versions of PostgresSQL range types. MobilityDB's period set type is conceptually an array of periods.

It would be great to have that information and some statistics to back it in the documentation. I was looking at the period type and was wondering why you reinvented what was already there and I had to search in the issues to find the reasons.

**Comment by estebanzimanyi** [comment]
Hello,

In the documentation of version 1.1 (the current develop branch) which will be available soon there is a section for migrating from version 1.0 to 1.1 (see below). Does this answer your question ?


![migrating](https://github.com/MobilityDB/MobilityDB/assets/26899974/cbaf5504-2e83-491c-94bc-1539029023b9)

**Comment by estebanzimanyi** [comment]
You are fully right !

However, we didn't want to put in the manual a negative comment wrt PostgreSQL since the whole MobilityDB project is ONLY possible thanks to PostgreSQL.

Our very initial version of MobilityDB many years ago used the tstzrange type from PostgreSQL, if only for code reuse but mainly to have less code to produce and maintain. Our initial benchmarks and profiling were not efficient enough given the huge size of the mobility datasets that we need to tackle nowadays. One of the first culprits was the tstzrange type since it is a variable-sized type and all the processing of the variable-size types requires many useless CPU cycles for MobilityDB since a period is simply a structure with two timestamps and a flag for the bounds. The range types in PostgreSQL have a much wider audience and their variable-size nature is fully justified, but this was unnecessary for us. This is why we started using a simple and very easy-to-code period type. Being of fixed-type we can use pointer arithmetics and thus binary search when we have an array of periods, which is not possible for an array of ranges.

The performance gains were immediately visible between the initial version of MobilityDB and the subsequent one with periods. Alas we didn't kept the measurements and it would be impossible to recover them now.

Does this better explain the rationale ?

Regards

Esteban

________________________________
De : Alexandre ***@***.***>
Envoyé : mercredi 24 mai 2023 19:23
À : MobilityDB/MobilityDB ***@***.***>
Cc : ZIMANYI Esteban ***@***.***>; Comment ***@***.***>
Objet : Re: [MobilityDB/MobilityDB] Data types precision? (Issue #250)


The original question I had was "Is preiod the same as tstzrange? And If so why did they rename it?" So the notes for the migration are not really answering that compared to the comment earlier that stated the performances gain on the period type compared to the tstzrange type. And if that information was present in the migration notes, it's not really where I would have looked for it. It's the kind of information I would see in the documentation of the period type and it would be nice to have stats that shows the gain of using period instead of tstzrange.

**Comment by belug23** [comment]
I don't see this as a negative for PostgreSQL, there's limits to every systems and having performances problems are a good justification for creating a new type that is similar enough to be confusing, but different enough to be more restrictive and have more performance.

I was just really confused because we've been doing the same thing with a tstzrange for years and I was looking at the documentation wondering "Why would I change, it's the same thing under a different name." I'm probably not be the only one wondering that.

**Comment by estebanzimanyi** [comment]
Thanks for your kind comments !
I will definitely add a summary of this exchange in the current version of the manual. I will let you know !
________________________________
De : Alexandre ***@***.***>
Envoyé : mercredi 24 mai 2023 20:46
À : MobilityDB/MobilityDB ***@***.***>
Cc : ZIMANYI Esteban ***@***.***>; Comment ***@***.***>
Objet : Re: [MobilityDB/MobilityDB] Data types precision? (Issue #250)


I don't see this as a negative for PostgreSQL, there's limits to every systems and having performances problems are a good justification for creating a new type that is similar enough to be confusing, but different enough to be more restrictive and have more performance.

I was just really confused because we've been doing the same thing with a tstzrange for years and I was looking at the documentation wondering "Why would I change, it's the same thing under a different name." I'm probably not be the only one wondering that.

**Comment by estebanzimanyi** [comment]
What about this sentence ?

![manual](https://github.com/MobilityDB/MobilityDB/assets/26899974/6db63dbb-80dd-48e1-a8e5-60f3a9b731b1)
