### ISSUE TITLE
MobilityDB and  postgis-trajenctory

### ISSUE THREAD

**Issue by amwps290** [MobilityDB/MobilityDB#288]
Hello, there was a PostGIS-Trajectory project, but I can't find it anymore. is there any difference between Mobility and PostGIS-Trajectory, or other features.

Thank you!

**Comment by estebanzimanyi** [comment]
Obviously there are FUNDAMENTAL differences between MobilityDB and PostGIS-Trajectory. 
I would suggest to read the extensive MobilityDB documentation in order to assess whether MobilityDB corresponds to what you are looking for.

**Comment by mschoema** [comment]
As a note to this, PostGIS-Trajectory provides a way to store trajectory data into a PostGIS LinestringM object, where the M-value stores the timestamps as second since EPOCH. This is built-in PostGIS, with mutliple functions that manipulate this type of data, such as _ST_IsValidTrajectory_, _ST_ClosestPointOfApproach_, _ST_CPAWithin_ and more. This set of functions for trajectories is, however, quite limited.

MobilityDB, on the other hand, extends PostGIS with trajectory-specific data types (tgeompoint and tgeogpoint), as well as scalar temporal types (tbool, tint, ttext, tfloat). These data types are more flexible and efficient for storing trajectory data and also comes with a much wider range of functions and operators, that can be found in the MobilityDB documentation as Esteban pointed out. Note also that the MobilityDB types tgeometry and tgeography can be cast into their respective PostGIS trajectory type (geometry(LinestringM) and geography(LinestringM)), so the two projects are not mutually exclusive.

**Comment by amwps290** [comment]
@mschoema Where can I find his source code? Want to learn it。

**Comment by mschoema** [comment]
You can find the MobilityDB documentation at [docs.mobilitydb.com/MobilityDB/develop/](https://docs.mobilitydb.com/MobilityDB/develop/) and, if needed, there is also more information available on the main [MobilityDB website](https://mobilitydb.com/), such as publication, the developers documentation and more.
The actual source code is here on github and you can also find some interesting information on the [repository wiki](https://github.com/MobilityDB/MobilityDB/wiki).

**Comment by amwps290** [comment]
@mschoema the PostGIS-Trajectory code or other useful information.Thank you!

**Comment by mschoema** [comment]
Here are a few useful links related to PostGIS trajectories:
- [Trajectory-specific PostGIS fuctions](https://postgis.net/docs/reference.html#Temporal). As you can see they are unfortunately quite limited.
- [List of blogs about PostGIS trajectories from Anita Graser](https://anitagraser.com/tag/postgis/)
- [Paper evaluating PostGIS trajectories](http://www.austriaca.at/0xc1aa5576_0x00390cbe). Tabe 1 in the paper contains a list of PostGIS functions that can be used to manipulate trajectories.
- The [home page](https://postgis.net/), [source code](https://git.osgeo.org/gitea/postgis/postgis) and its [documentation](https://postgis.net/docs/)
