### ISSUE TITLE
ERROR:  type "intset" already exists

### ISSUE THREAD

**Issue by ankoure** [MobilityDB/MobilityDB#485]
**Describe the bug**
When creating the MobilityDB extension in psql the following error is returned: ERROR:  type "intset" already exists

**To Reproduce**
1.  Compile MobilityDB on Debian
2.  ```SQL create extension MobilityDB; ```
3.  See error

**Expected behavior**
I expected CREATE EXTENSION to be returned. 

**Sample Data**
If applicable, add sample data to help explain your problem.

**Screenshots**

![image](https://github.com/MobilityDB/MobilityDB/assets/50218177/fc19e6de-935a-4fdc-aa46-4c938b2ccb32)

**Specifications (please complete the following information):**
Use the commands:
```SQL
SELECT version();
SELECT postgis_full_version();
SELECT mobilitydb_full_version();
```
```SQL
version
---------------------------------------------------------------------------------------------------------------------
 PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

postgis_full_version
------------------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="3.4.2 c19ce56" [EXTENSION] PGSQL="160" GEOS="3.11.1-CAPI-1.17.1" PROJ="9.1.1 NETWORK_ENABLED=OFF URL_ENDPOINT=https://cdn.proj.org USER_WRITABLE_DIRECTORY=/tmp/proj DATABASE_PATH=/usr/share/proj/proj.db" LIBXML="2.9.14" LIBJSON="0.16" LIBPROTOBUF="1.4.1" WAGYU="0.5.0 (Internal)"

ERROR:  function mobilitydb_full_version() does not exist
LINE 1: SELECT mobilitydb_full_version();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

```
Attempting to install MobilityDB Version 1.1.1

**Additional context**

**Comment by mschoema** [comment]
This is surprising. Could it be possible that you have another extension which also creates a type called `intset`? To check if your database already contains the `intset` type, you can run `\dT intset` in psql. If the query returned a row, this means you already have a type called `intset` and installing mobilitydb will indeed not be possible. If this is the case, let us know which other extension also contains this type, so we can try to coordinate to avoid this problem.

Otherwise, if `\dT intset` did not return any rows, then something went wrong with the mobilitydb sql extension script. Normally, if you built mobilitydb using `make`, you should end up with a file called `mobilitydb--1.1.1.sql` in your build directory. Could you search this file to verify that it indeed only contains 2 lines with `CREATE EXTENSION intset`? The following should be present somewhere at the top of the file:

```
...

CREATE TYPE intset;
CREATE TYPE ...
...

CREATE FUNCTION intset_in(cstring)
  ...
...

...

CREATE TYPE intset (
  internallength = variable,
  input = intset_in,
  output = intset_out,
  receive = intset_recv,
  send = intset_send,
  alignment = double,
  storage = extended,
  analyze = span_analyze
);

...
```

**Comment by ankoure** [comment]
The pql command did not return any results. 

![image](https://github.com/MobilityDB/MobilityDB/assets/50218177/b90dfb90-b61d-439d-a9a0-ccdfad2d9e9b)

The .sql file seems to be in order but I uploaded it in case I missed anything. 

[mobilitydb--1.1.1.zip](https://github.com/MobilityDB/MobilityDB/files/15214986/mobilitydb--1.1.1.zip)

**Comment by mschoema** [comment]
There indeed seems to  be something going wrong with the mobilitydb--1.1.1.sql file.

```bash
$ cat mobilitydb--1.1.1.sql | grep "CREATE TYPE intset"
CREATE TYPE intset;
CREATE TYPE intset (
CREATE TYPE intset;
CREATE TYPE intset (
CREATE TYPE intset;
CREATE TYPE intset (
```

This can happen after calling `cmake` multiple times in your build directory without emptying it first:
```bash
MobilityDB/build $ rm -rf *
MobilityDB/build $ cmake ..
...
MobilityDB/build $ cat mobilitydb--1.1.1.sql | grep "CREATE TYPE intset"
CREATE TYPE intset;
CREATE TYPE intset (
MobilityDB/build $ cmake ..
...
MobilityDB/build $ cat mobilitydb--1.1.1.sql | grep "CREATE TYPE intset"
CREATE TYPE intset;
CREATE TYPE intset (
CREATE TYPE intset;
CREATE TYPE intset (
```

Try emptying you build directory then re-building mobilitydb with a single `cmake` call.

**Comment by ankoure** [comment]
Emptying the build directory and re-building mobilitydb worked! Thank you so much!
