### ISSUE TITLE
Travis & Coveralls

### ISSUE THREAD

**Issue by cvvergara** [MobilityDB/MobilityDB#98]
From the comment https://github.com/MobilityDB/MobilityDB/issues/85#issuecomment-884678782
> Is the file travis.yml still needed ? I think it is redundant with the new workflow.

Travis is used in the coverage/coveralls CI
tasks:
- [ ] add an action for the coverage/calls
- [ ] link  coverage/calls to the action
- [ ] remove travis

**Comment by estebanzimanyi** [comment]
@cvvergara Do you think you can help to identify the problem with coveralls ?

In PR 89 the coverall tests worked 
https://github.com/MobilityDB/MobilityDB/pull/89

You can verify this on your local machine by installing the necessary package, creating a local copy of the repository at that commit, and do a full build (assuming you are in MobilityDB/build for the following commands)

pip install cpp-coveralls
git checkout -b test-branch 84713f4
rm -rf *
cmake -DWITH_COVERAGE=1 ..
make && make test
coveralls --exclude cmake --exclude doc --exclude include --exclude sql --exclude src --exclude test --exclude tools --gcov-options '\-lp' -r .. -b .
File '/home/esteban/src/MobilityDB/src/tinstantset.c'
Lines executed:99.37% of 631
Creating '#home#esteban#src#MobilityDB#build#CMakeFiles#MobilityDB.dir#src#tinstantset.c.o###home#esteban#src#MobilityDB#src#tinstantset.c.gcov'
[...]

On the contrary, on the current version of the repository the above steps yield errors

Information about gcov can be found here
https://gcc.gnu.org/onlinedocs/gcc/Gcov.html

Since you know better all the changes you made in cmake, could you please add incrementally all the changes you did for PR #90 to understand when the workflow for coveralls broke ?

**Comment by estebanzimanyi** [comment]
A useful resource is 
https://about.codecov.io/blog/how-to-set-up-codecov-with-c-and-github-actions/

**Comment by cvvergara** [comment]
Will worry about this after I finish with all the build organization

**Comment by cvvergara** [comment]
@estebanzimanyi 
Response to comment here
https://github.com/MobilityDB/MobilityDB/issues/85#issuecomment-887604050

I don't know, I haven't even started reading the documentation of coveralls.

But it might be that the structure changed again.

**Comment by estebanzimanyi** [comment]
Coverage solved with PR #139 . Travis still kept for generating detailed log information which Github Actions lacks.
